### ISSUE TITLE
[FEATURE] Better Constant width to height ratio

### ISSUE THREAD

**Issue by xialvjun** [atomiks/30-seconds-of-css#64]
```css
.better-constant-width-to-height-ratio {
  background: #333;
  width: 50%;
}
.better-constant-width-to-height-ratio::before {
  content: ' ';
  display: block;
  padding-top: 100%;
  float: left;
}
.better-constant-width-to-height-ratio::after {
  content: ' ';
  display: block;
  clear: both;
}
```

No need to worry about padding.
